### 1. Installation

The parser has not requirents but for the Python

In [1]:
from tg_json_parser import TgJsonParser

### 2. Getting the telegram data

1. Open the channel you want to download, clock on three dots in right top korner of the chat
2. Choose export chat history
3. Change the format from HTML to machine-readable JSON

### 3. Parcing data

In [2]:
# (replace sample data with your own file)
chat_path = 'data/raw/Sample_ChatExport/result.json'

In [3]:
# Load the chat data from the JSON file
tg_parcer = TgJsonParser()
tg_parcer.load_json(chat_path)

In [4]:
# Parcing data
# (this will take some time depending on the size of the chat)
tg_parcer.extract_messages()
tg_parcer.name

'WarRoom: Official Telegram Channel'

In [5]:
# Save the parsed data to a CSV
tg_parcer.save_chat(output_path='data/processed/Sample_Chat')

In [11]:
import pandas as pd

pd.DataFrame(tg_parcer.member_actions)

,id,type,date,date_unixtime,actor,actor_id,action,text,text_entities,chat_name,message_id,duration
0,74315,service,2025-07-01T18:41:49,1751384509,WarRoom: Official Telegram Channel,channel1211378130,group_call,,[],WarRoom: Official Telegram Channel,NaN,NaN
1,74383,service,2025-07-02T12:56:19,1751450179,WarRoom: Official Telegram Channel,channel1211378130,group_call,,[],WarRoom: Official Telegram Channel,NaN,NaN
2,74471,service,2025-07-03T20:09:12,1751562552,WarRoom: Official Telegram Channel,channel1211378130,group_call,,[],WarRoom: Official Telegram Channel,NaN,NaN
3,74475,service,2025-07-03T23:37:29,1751575049,WarRoom: Official Telegram Channel,channel1211378130,group_call,,[],WarRoom: Official Telegram Channel,NaN,NaN
4,74523,service,2025-07-04T12:17:01,1751620621,WarRoom: Official Telegram Channel,channel1211378130,group_call,,[],WarRoom: Official Telegram Channel,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
62,77290,service,2025-08-15T14:16:35,1755256595,WarRoom: Official Telegram Channel,channel1211378130,group_call,,[],WarRoom: Official Telegram Channel,NaN,NaN
63,77313,service,2025-08-15T17:10:59,1755267059,WarRoom: Official Telegram Channel,channel1211378130,group_call,,[],WarRoom: Official Telegram Channel,NaN,10464.0
64,77314,service,2025-08-15T17:11:02,1755267062,WarRoom: Official Telegram Channel,channel1211378130,group_call,,[],WarRoom: Official Telegram Channel,NaN,NaN
65,77505,service,2025-08-19T02:46:20,1755560780,WarRoom: Official Telegram Channel,channel1211378130,group_call,,[],WarRoom: Official Telegram Channel,NaN,46421.0
66,77510,service,2025-08-19T03:06:28,1755561988,WarRoom: Official Telegram Channel,channel1211378130,group_call,,[],WarRoom: Official Telegram Channel,NaN,NaN

In [6]:
# Save the parsed data and mamber_actions to a CSV
tg_parcer.save_chat(output_path='data/processed/Sample_Chat', save_actions=True)

In [8]:
# Pandas is not required for the main functionality.
# It is used here to preview the data in a DataFrame format.
import pandas as pd 

df_messages = pd.DataFrame(tg_parcer.content_messages)
df_messages

,msg_id,sender,sender_id,reply_to_msg_id,forwarded_from,reactions,posting_time,edited,media_type,content,file,file_name,chat_name
0,74271,WarRoom: Official Telegram Channel,channel1211378130,None,None,"[{'type': 'emoji', 'count': 26, 'emoji': '🫡'},...",2025-06-30 22:04:48,2025-06-30 22:05:33,photo,BANNON’S WARROOM BATTLEGROUND EVENING EDITION ...,photos/photo_39885@01-07-2025_01-04-48.jpg,None,WarRoom: Official Telegram Channel
1,74272,WarRoom: Official Telegram Channel,channel1211378130,None,None,"[{'type': 'emoji', 'count': 93, 'emoji': '🤡'},...",2025-06-30 22:11:09,2025-06-30 22:12:07,photo,,photos/photo_39886@01-07-2025_01-11-09.jpg,None,WarRoom: Official Telegram Channel
2,74274,WarRoom: Official Telegram Channel,channel1211378130,None,None,"[{'type': 'emoji', 'count': 75, 'emoji': '❤'},...",2025-06-30 22:20:12,2025-06-30 22:21:29,photo,The One Big Beautiful Bill will boost economic...,photos/photo_39887@01-07-2025_01-20-12.jpg,None,WarRoom: Official Telegram Channel
3,74275,WarRoom: Official Telegram Channel,channel1211378130,None,None,"[{'type': 'emoji', 'count': 78, 'emoji': '❤'},...",2025-06-30 22:20:15,2025-06-30 22:21:51,photo,,photos/photo_39888@01-07-2025_01-20-15.jpg,None,WarRoom: Official Telegram Channel
4,74276,WarRoom: Official Telegram Channel,channel1211378130,None,None,"[{'type': 'emoji', 'count': 112, 'emoji': '🤬'}...",2025-06-30 22:31:37,2025-06-30 22:31:49,photo,"We’re told these are “socialists”, so meet the...",photos/photo_39889@01-07-2025_01-31-37.jpg,None,WarRoom: Official Telegram Channel
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3015,77523,WarRoom: Official Telegram Channel,channel1211378130,None,None,"[{'type': 'emoji', 'count': 83, 'emoji': '❤‍🔥'...",2025-08-19 03:41:36,2025-08-19 03:42:41,photo,Historic Day @ the White House and in the Oval...,photos/photo_42022@19-08-2025_06-41-36.jpg,None,WarRoom: Official Telegram Channel
3016,77525,WarRoom: Official Telegram Channel,channel1211378130,None,WarRoom Live-Stream 🇺🇸,None,2025-08-19 14:00:24,2025-08-19 14:00:28,photo,BANNON’S WARROOM LIVE! 🦅🇺🇸🦅 \n\nLive-Streaming...,photos/photo_39925@02-07-2025_00-05-27.jpg,None,WarRoom: Official Telegram Channel
3017,77526,WarRoom: Official Telegram Channel,channel1211378130,None,None,"[{'type': 'emoji', 'count': 11, 'emoji': '🤣'},...",2025-08-19 14:01:00,2025-08-19 14:03:15,video_file,🇺🇸🇺🇸🇺🇸 \n\n*re-edited version 🫡 😊\n\nMorning ...,(File not included. Change data exporting sett...,IMG_3340.MP4,WarRoom: Official Telegram Channel
3018,77527,WarRoom: Official Telegram Channel,channel1211378130,None,WarRoom: Official Telegram Channel,None,2025-08-19 14:08:07,2025-08-19 14:08:11,photo,NBC Kicks Trash to the Curb\n\n https://x.com/...,photos/photo_42019@19-08-2025_06-35-13.jpg,None,WarRoom: Official Telegram Channel
3019,77528,WarRoom: Official Telegram Channel,channel1211378130,None,None,"[{'type': 'emoji', 'count': 1, 'emoji': '💯'}]",2025-08-19 14:08:21,2025-08-19 14:09:17,photo,"Weak, Feckless Europe Looks to US for Financia...",photos/photo_42025@19-08-2025_17-08-21.jpg,None,WarRoom: Official Telegram Channel